### ISSUE TITLE
Dependency requirements are too loose

### ISSUE THREAD

**Issue by alexandrucosminmihai** [msg-systems/coreferee#4] opened 2021-05-23 20:49 UTC
The current dependency requirements are too loose, causing a fresh install that uses the newest versions of the dependencies, where applicable (where >= is used for the version number), to not work with different errors.

Alternatively, the code is not compatible with the newest versions of the depdendencies.

I managed to run the example using the lowest allowed versions of the dependencies (replacing >= with ==):
h5py==2.10.0 keras==2.4.3 numpy==1.19.2 spacy==3.0.5 tensorflow==2.4.1

**Comment by richardpaulhudson** [comment] 2021-05-24 09:37
I reinstalled everything in a clean environment and was unable to reproduce any problem. Could you please supply more information about your environment (OS etc.) and details of what exactly went wrong?

**Comment by richardpaulhudson** [comment] 2021-06-07 09:38
Closing as there has been no further activity.

**Closed by richardpaulhudson** 2021-06-07 09:38 UTC
Labels: question
