### ISSUE TITLE
pip install does not work (can not find package)

### ISSUE THREAD

**Issue by Peter-E-Lenz** [msg-systems/coreferee#7] opened 2021-06-09 14:53 UTC
$ python --version
Python 3.9.5

$pip --version
pip 21.1.1 from <SNIP>/lib/python3.9/site-packages/pip (python 3.9)

$ pip install coreferee
ERROR: Could not find a version that satisfies the requirement coreferee (from versions: none)
ERROR: No matching distribution found for coreferee

**Comment by richardpaulhudson** [comment] 2021-06-09 14:56
Duplicate of issue #6.

**Closed by richardpaulhudson** 2021-06-09 14:56 UTC
Labels: duplicate
